import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import SignInSide from "./SignInSide";
import Layout from "@/components/Layoutmain";
import Container from "@material-ui/core/Container";
import Title from "@/components/Title";
import First from "@/components/First";

export default function Home() {
  return (
    <React.StrictMode>
      <div>
        <Head>
          <title>SISMED</title>
          <meta name="description" content="Generated by sismed" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/*<SignInSide />*/}
      </div>

      <Container maxWidth="lg">
        <First />
      </Container>
    </React.StrictMode>
  );
}
